# 天气更新通知
name: moments

on: 
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *"    
  push:
    branches: main
   
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      QMSG_KEY: ${{ secrets.QMSG_KEY }} 
      CITY_CODE: ${{ secrets.CITY_CODE }}
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Set up Python #安装python
      uses: actions/setup-python@main
      with:
        python-version: 3.8
    - name: Weather Notice #更新
      run: | 
        pip install requests
        pip install os
        python py/weather.py
    - name: Delete Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
